### ISSUE TITLE
Add context.Context monitoring

### ISSUE THREAD

**Issue by cedric-appdirect** [tavsec/gin-healthcheck#16]
I think it would be useful to have a check for context.Context as that could be used to implement part of kubernetes graceful shutdown by watching for the term signal and switching to a non ready state on that signal (description of what is expected to happen with nice graphics: https://blog.risingstack.com/graceful-shutdown-node-js-kubernetes/ ).

If you are ok with such a contribution, I will do a PR shortly.

**Comment by tavsec** [comment]
@cedric-appdirect this sounds like a great improvement. Feel free to open PR 👍

**Comment by cedric-appdirect** [comment]
Thanks will work on it.
